const TICK_MODE = 'tick'
const BAR_MODE = 'bar'

const STOP_ORDER_PREFIX = 'CtaStopOrder'

const ENGINETYPE_BACKTESTING = 'backtesting'

// 状态常量
const STATUS_NOTTRADED = '未成交'
const STATUS_PARTTRADED = '部分成交'
const STATUS_ALLTRADED = '全部成交'
const STATUS_CANCELLED = '已撤销'
const STATUS_REJECTED = '拒单'
const STATUS_UNKNOWN = '未知'

// 方向常量
const DIRECTION_LONG = '多'
const DIRECTION_SHORT = '空'
const DIRECTION_UNKNOWN = '未知'

module.exports = {
  TICK_MODE,
  BAR_MODE,
  STOP_ORDER_PREFIX,
  ENGINETYPE_BACKTESTING,
  STATUS_NOTTRADED,
  STATUS_PARTTRADED,
  STATUS_ALLTRADED,
  STATUS_CANCELLED,
  STATUS_REJECTED,
  STATUS_UNKNOWN,
  DIRECTION_LONG,
  DIRECTION_SHORT,
  DIRECTION_UNKNOWN
}